version: 1.1.3
path: ClipNuke.exe
# sha512: Dj51I0q8aPQ3ioaz9LMqGYujAYRbDNblAQbodDRXAMxmY6hsHqEl3F6SvhfJj5oPhcqdX1ldsgEvfMNXGUXBIw==
stagingPercentage: 100
trigger:
    - master

pool:
    vmImage: 'windows-2019'

steps:
- task: Npm@0
    inputs:
        command: 'install'
    displayName: 'npm install'

- task: Npm@1
    inputs:
        command: 'custom'
        customCommand: 'run package-win'
    displayName: 'npm run package-win'
